name: Deploy Version 2

on: 
    push:
        branches:
            - main
        paths-ignore:
            - readme.md

    
    workflow_dispatch:

jobs:
    test1:
        runs-on: ubuntu-latest

        steps:
            - name: Getting the code from GH Repo
              uses: actions/checkout@v4

            - name: Install Node js
              uses: actions/setup-node@v4
              with:
                node-version: 18
            
            - name: Cache Dependencies
              uses: actions/cache@v4
              with:
                path : ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            
            - name: Install Dependencies
              run: npm ci 
              # we are usin npm ci because now we have package-lock file in the root directory

            - name: Run the test
              run: npm run test
    test2:
        runs-on: ubuntu-latest
        #needs: test1
        steps:
            - name: Job 2 worked!
              run: echo "Hey this is working, that is awesome!"

    Deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            
            - name: Install Node js
              uses: actions/setup-node@v4
              with:
                node-version: 18
            
            - name: Cache Dependencies
            # Caching the Dependencies from the Earlier test1
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            
            - name: Install Dependencies
              run: npm ci
            
            - name: Everthing Worked
              run: echo "Everthing worked!"
       

